<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Config', 'doctrine');

/**
 * BaseConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $max_age
 * @property string $origin
 * @property integer $origin_radius
 * @property string $destination
 * @property integer $destination_radius
 * @property integer $frequence
 * @property Doctrine_Collection $JobboardConfigs
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getMaxAge()             Returns the current record's "max_age" value
 * @method string              getOrigin()             Returns the current record's "origin" value
 * @method integer             getOriginRadius()       Returns the current record's "origin_radius" value
 * @method string              getDestination()        Returns the current record's "destination" value
 * @method integer             getDestinationRadius()  Returns the current record's "destination_radius" value
 * @method integer             getFrequence()          Returns the current record's "frequence" value
 * @method Doctrine_Collection getJobboardConfigs()    Returns the current record's "JobboardConfigs" collection
 * @method Config              setId()                 Sets the current record's "id" value
 * @method Config              setMaxAge()             Sets the current record's "max_age" value
 * @method Config              setOrigin()             Sets the current record's "origin" value
 * @method Config              setOriginRadius()       Sets the current record's "origin_radius" value
 * @method Config              setDestination()        Sets the current record's "destination" value
 * @method Config              setDestinationRadius()  Sets the current record's "destination_radius" value
 * @method Config              setFrequence()          Sets the current record's "frequence" value
 * @method Config              setJobboardConfigs()    Sets the current record's "JobboardConfigs" collection
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('max_age', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('origin', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('origin_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('destination', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('destination_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('frequence', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobboardConfig as JobboardConfigs', array(
             'local' => 'id',
             'foreign' => 'config_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}