<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Loads', 'doctrine');

/**
 * BaseLoads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $reference
 * @property integer $jobboard_id
 * @property time $age
 * @property date $date
 * @property integer $truck_id
 * @property enum $loads_type
 * @property string $origin
 * @property integer $origin_radius
 * @property string $destination
 * @property integer $destination_radius
 * @property string $contact
 * @property integer $distance
 * 
 * @method integer getId()                 Returns the current record's "id" value
 * @method string  getReference()          Returns the current record's "reference" value
 * @method integer getJobboardId()         Returns the current record's "jobboard_id" value
 * @method time    getAge()                Returns the current record's "age" value
 * @method date    getDate()               Returns the current record's "date" value
 * @method integer getTruckId()            Returns the current record's "truck_id" value
 * @method enum    getLoadsType()          Returns the current record's "loads_type" value
 * @method string  getOrigin()             Returns the current record's "origin" value
 * @method integer getOriginRadius()       Returns the current record's "origin_radius" value
 * @method string  getDestination()        Returns the current record's "destination" value
 * @method integer getDestinationRadius()  Returns the current record's "destination_radius" value
 * @method string  getContact()            Returns the current record's "contact" value
 * @method integer getDistance()           Returns the current record's "distance" value
 * @method Loads   setId()                 Sets the current record's "id" value
 * @method Loads   setReference()          Sets the current record's "reference" value
 * @method Loads   setJobboardId()         Sets the current record's "jobboard_id" value
 * @method Loads   setAge()                Sets the current record's "age" value
 * @method Loads   setDate()               Sets the current record's "date" value
 * @method Loads   setTruckId()            Sets the current record's "truck_id" value
 * @method Loads   setLoadsType()          Sets the current record's "loads_type" value
 * @method Loads   setOrigin()             Sets the current record's "origin" value
 * @method Loads   setOriginRadius()       Sets the current record's "origin_radius" value
 * @method Loads   setDestination()        Sets the current record's "destination" value
 * @method Loads   setDestinationRadius()  Sets the current record's "destination_radius" value
 * @method Loads   setContact()            Sets the current record's "contact" value
 * @method Loads   setDistance()           Sets the current record's "distance" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLoads extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('loads');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('reference', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('jobboard_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('age', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('truck_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('loads_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'FULL',
              1 => 'PARTIAL',
              2 => 'BOTH',
             ),
             'notnull' => true,
             'default' => 'FULL',
             ));
        $this->hasColumn('origin', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('origin_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('destination', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('destination_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('contact', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('distance', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}