<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Loads', 'doctrine');

/**
 * BaseLoads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $hash
 * @property string $web_reference
 * @property integer $jobboard_id
 * @property date $date
 * @property string $truck_type
 * @property string $loads_type
 * @property string $origin
 * @property integer $origin_radius
 * @property string $destination
 * @property integer $destination_radius
 * @property string $contact
 * @property integer $distance
 * @property string $company
 * 
 * @method string  getHash()               Returns the current record's "hash" value
 * @method string  getWebReference()       Returns the current record's "web_reference" value
 * @method integer getJobboardId()         Returns the current record's "jobboard_id" value
 * @method date    getDate()               Returns the current record's "date" value
 * @method string  getTruckType()          Returns the current record's "truck_type" value
 * @method string  getLoadsType()          Returns the current record's "loads_type" value
 * @method string  getOrigin()             Returns the current record's "origin" value
 * @method integer getOriginRadius()       Returns the current record's "origin_radius" value
 * @method string  getDestination()        Returns the current record's "destination" value
 * @method integer getDestinationRadius()  Returns the current record's "destination_radius" value
 * @method string  getContact()            Returns the current record's "contact" value
 * @method integer getDistance()           Returns the current record's "distance" value
 * @method string  getCompany()            Returns the current record's "company" value
 * @method Loads   setHash()               Sets the current record's "hash" value
 * @method Loads   setWebReference()       Sets the current record's "web_reference" value
 * @method Loads   setJobboardId()         Sets the current record's "jobboard_id" value
 * @method Loads   setDate()               Sets the current record's "date" value
 * @method Loads   setTruckType()          Sets the current record's "truck_type" value
 * @method Loads   setLoadsType()          Sets the current record's "loads_type" value
 * @method Loads   setOrigin()             Sets the current record's "origin" value
 * @method Loads   setOriginRadius()       Sets the current record's "origin_radius" value
 * @method Loads   setDestination()        Sets the current record's "destination" value
 * @method Loads   setDestinationRadius()  Sets the current record's "destination_radius" value
 * @method Loads   setContact()            Sets the current record's "contact" value
 * @method Loads   setDistance()           Sets the current record's "distance" value
 * @method Loads   setCompany()            Sets the current record's "company" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLoads extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('loads');
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('web_reference', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('jobboard_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('truck_type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('loads_type', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('origin', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('origin_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('destination', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('destination_radius', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('contact', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('distance', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}