<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Truck', 'doctrine');

/**
 * BaseTruck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $ConfigTrucks
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getConfigTrucks() Returns the current record's "ConfigTrucks" collection
 * @method Truck               setId()           Sets the current record's "id" value
 * @method Truck               setName()         Sets the current record's "name" value
 * @method Truck               setConfigTrucks() Sets the current record's "ConfigTrucks" collection
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTruck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('truck');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => 'trye',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConfigTruck as ConfigTrucks', array(
             'local' => 'id',
             'foreign' => 'truck_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}