<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Jobboard', 'doctrine');

/**
 * BaseJobboard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property integer $config_id
 * @property integer $generator_id
 * @property JobboardConfig $Config
 * @property Generator $Generator
 * 
 * @method integer        getId()           Returns the current record's "id" value
 * @method string         getName()         Returns the current record's "name" value
 * @method string         getAddress()      Returns the current record's "address" value
 * @method integer        getConfigId()     Returns the current record's "config_id" value
 * @method integer        getGeneratorId()  Returns the current record's "generator_id" value
 * @method JobboardConfig getConfig()       Returns the current record's "Config" value
 * @method Generator      getGenerator()    Returns the current record's "Generator" value
 * @method Jobboard       setId()           Sets the current record's "id" value
 * @method Jobboard       setName()         Sets the current record's "name" value
 * @method Jobboard       setAddress()      Sets the current record's "address" value
 * @method Jobboard       setConfigId()     Sets the current record's "config_id" value
 * @method Jobboard       setGeneratorId()  Sets the current record's "generator_id" value
 * @method Jobboard       setConfig()       Sets the current record's "Config" value
 * @method Jobboard       setGenerator()    Sets the current record's "Generator" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobboard extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobboard');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('config_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('generator_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JobboardConfig as Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));

        $this->hasOne('Generator', array(
             'local' => 'generator_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}