<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notify', 'doctrine');

/**
 * BaseNotify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notify_id
 * @property string $content
 * @property boolean $status
 * 
 * @method integer getNotifyId()  Returns the current record's "notify_id" value
 * @method string  getContent()   Returns the current record's "content" value
 * @method boolean getStatus()    Returns the current record's "status" value
 * @method Notify  setNotifyId()  Sets the current record's "notify_id" value
 * @method Notify  setContent()   Sets the current record's "content" value
 * @method Notify  setStatus()    Sets the current record's "status" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notify');
        $this->hasColumn('notify_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}