<?php

/**
 * GeneratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneratorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Generator');
    }
}