<?php

/**
 * JobboardConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobboardConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobboardConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobboardConfig');
    }
	public function deleteConfigId($config_id){
		$q = $this->createQuery('j')
            ->where('j.config_id = ?',$config_id);
        $result = $q->execute();
        $result->delete();
	}
}