<?php

/**
 * JobboardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobboardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobboardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jobboard');
    }
}