# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules

default:
  url:  /default
  param: { module: default, action: index }
  
default_logout:
  url:  /default/logout
  param: { module: default, action: logout }

# users  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
sf_guard_user:
  url:   /user
  param: { module: sfGuardUser, action: index }

# others
loads:
  url:   /loads
  param: { module: loads, action: index }
  
config:
  url:   /config
  param: { module: config, action: index }
 
config_create:
  url:   /config/create
  param: { module: config, action: edit }
  
config_edit:
  url:   /config/edit/:config_id
  param: { module: config, action: edit }
config_delete:
  url:   /config/delete/:config_id
  param: { module: config, action: delete }
  
quick_search:
  url: /quick_search
  param: { module: quickSearch, action: index }

quick_search_reload:
  url: /quick_search_reload
  param: { module: quickSearch, action: reload }