# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, frontend/main.css, jquery-ui.css]

  javascripts:
    - "jquery/jquery.min.js"
    - "jquery/jquery-ui.min.js"
    - "jquery/jquery.ui.core.js"
    - "jquery/jquery.ui.widget.js"
    - "jquery/jquery.ui.datepicker.js"
    - "jquery/jquery.ui.datepicker-vi.js"
    - "tiny_mce/tiny_mce.js"
    - "frontend.js"

  has_layout:     true
  layout:         layout
