<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JobboardConfig', 'doctrine');

/**
 * BaseJobboardConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $jobboard_id
 * @property integer $config_id
 * @property Jobboard $Jobboard
 * @property Config $Config
 * 
 * @method integer        getJobboardId()  Returns the current record's "jobboard_id" value
 * @method integer        getConfigId()    Returns the current record's "config_id" value
 * @method Jobboard       getJobboard()    Returns the current record's "Jobboard" value
 * @method Config         getConfig()      Returns the current record's "Config" value
 * @method JobboardConfig setJobboardId()  Sets the current record's "jobboard_id" value
 * @method JobboardConfig setConfigId()    Sets the current record's "config_id" value
 * @method JobboardConfig setJobboard()    Sets the current record's "Jobboard" value
 * @method JobboardConfig setConfig()      Sets the current record's "Config" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobboardConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobboard_config');
        $this->hasColumn('jobboard_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('config_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jobboard', array(
             'local' => 'jobboard_id',
             'foreign' => 'id'));

        $this->hasOne('Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}