<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConfigTruck', 'doctrine');

/**
 * BaseConfigTruck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $config_id
 * @property integer $truck_id
 * @property Config $Config
 * @property Truck $Truck
 * 
 * @method integer     getConfigId()  Returns the current record's "config_id" value
 * @method integer     getTruckId()   Returns the current record's "truck_id" value
 * @method Config      getConfig()    Returns the current record's "Config" value
 * @method Truck       getTruck()     Returns the current record's "Truck" value
 * @method ConfigTruck setConfigId()  Sets the current record's "config_id" value
 * @method ConfigTruck setTruckId()   Sets the current record's "truck_id" value
 * @method ConfigTruck setConfig()    Sets the current record's "Config" value
 * @method ConfigTruck setTruck()     Sets the current record's "Truck" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfigTruck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config_truck');
        $this->hasColumn('config_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('truck_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Config', array(
             'local' => 'config_id',
             'foreign' => 'id'));

        $this->hasOne('Truck', array(
             'local' => 'truck_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}