<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Generator', 'doctrine');

/**
 * BaseGenerator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Jobboard $Jobboard
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method string    getName()     Returns the current record's "name" value
 * @method Jobboard  getJobboard() Returns the current record's "Jobboard" value
 * @method Generator setId()       Sets the current record's "id" value
 * @method Generator setName()     Sets the current record's "name" value
 * @method Generator setJobboard() Sets the current record's "Jobboard" value
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGenerator extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('generator');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jobboard', array(
             'local' => 'id',
             'foreign' => 'generator_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}