# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules

default:
  url:  /default
  param: { module: default, action: index }
  
default_logout:
  url:  /default/logout
  param: { module: default, action: logout }
loads:
  url:   /loads
  param: { module: loads, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
sf_guard_user:
  url:   /user
  param: { module: sfGuardUser, action: index }
