<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/31 04:19:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=emc',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
