<?php

/**
 * ConfigTruckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigTruckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigTruckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConfigTruck');
    }
}