<?php

/**
 * JobboardConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobboardConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobboardConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobboardConfig');
    }
}