<?php

/**
 * Loads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    emc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Loads extends BaseLoads
{
	public function getCurrentLoadsAge() {
		$age = strtotime("now") - strtotime($this->created_at);
		$hour = floor($age/3600);
		$minutes = floor(($age - $hour * 3600)/60);
		return $hour.':'.$minutes;
	}
}
