<?php

/**
 * LoadsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoadsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoadsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Loads');
    }
}