<?php

/**
 * TruckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TruckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TruckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Truck');
    }
}